### PR TITLE
Add class which generates a valid Google Translate token.

### PR DESCRIPTION
**Pull request by tehmaestro**
So here is the class. I included a function which generates the "b" parameter too. I kept the same names as the javascript functions, because I think this will make it easier to understand what's going on, and perhaps easier to modify in the future.

### CODE REVIEW

**Comment by limonte** [comment]
@tehmaestro nicely done!

**Comment by Stichoza** [comment]
Thanks @tehmaestro and @helen5106! :+1: #32 is now mostly fixed ^_^ Array translation test still remains red but it's ok at this moment.

screen shot 2015-12-23 at 00 00 58

**Comment by johndag76** [comment]
Thank you Stichoza good news :) :) Please keep up updated when the new official release of the library will be ready :+1:

**Comment by Stichoza** [comment]
Oh I forgot to push a new tag. Thanks for reminding. I'll create a new tag that works without array translation

**Comment by stevebauman** [comment]
@tehmaestro awesome work! And thanks @Stichoza for pushing these updates so out so quickly :)

**Pull request merged**
