### PR TITLE
change the default source parameter in setSource to 'auto' like in __con...

### PR DESCRIPTION
**Pull request by subsan**
...struct

Propose to remove the one comparison and bring a piece of code to the same species

### CODE REVIEW

**Comment by Stichoza** [comment]
I have already thought about this but decided `null` to be a default parameter for `setSource()` method.

I'm actually hiding `"auto"` string from the whole code. It doesn't need to have two same options (`null` and `"auto"`). So `null` means auto itself and any other string is considered as locale identifier.

P.S. Seems that I forgot to change default parameter to `null` in constructor, so it would be better to change constructor instead. Plus, removing `null` from code will cause backwards incompatible changes.

**Comment by Stichoza** [comment]
Also there is `null` stated in examples/docs in [language-detection](https://github.com/Stichoza/google-translate-php#language-detection) section. So removing comparison will break code unless we bump a major version like 4.0 (according to semver) and change docs.

**Comment by subsan** [comment]
Yes, I agree. I saw it already after sent a request, so shut it. This situation will need to add a test because my changes did not have to take the test, but passed.

**Comment by Stichoza** [comment]
Yeah, I don't have full code coverage. It's actually my first time playing with tests.

**Pull request closed without merging**
