### PR TITLE
 Allow using getResponse() method to get raw translations data.

### PR DESCRIPTION
**Pull request by limonte**
In some cases we need to get raw array response from Google and then use it in custom way.

I think in older versions of `google-translate-php` there was such functionality, but currently there is no.

This pull request allows to use plugin this way:

```php
$tr = new TranslateClient();
$tr->setSource('en');
$tr->setTarget('sr');

$gt = $tr->getResponse($word);
```

`$gt` will contain raw array data from Google Translate, e.g.:

```
array(7) {
  [0]=>
  array(1) {
    [0]=>
    array(5) {
      [0]=>
      string(39) "телевизијска емисија"
      [1]=>
      string(8) "telecast"
      [2]=>
      string(20) "televizijska emisija"
      [3]=>
      string(0) ""
      [4]=>
      int(0)
    }
  }
  [1]=>
  array(2) {
    [0]=>
    array(5) {
      [0]=>
      string(4) "noun"
      [1]=>
      array(1) {
        [0]=>
        string(39) "телевизијска емисија"
      }
      [2]=>
      array(1) {
        [0]=>
        array(2) {
          [0]=>
          string(39) "телевизијска емисија"
          [1]=>
          array(2) {
            [0]=>
            string(8) "telecast"
            [1]=>
            string(15) "television show"
          }
        }
      }
      [3]=>
      string(8) "telecast"
      [4]=>
      int(1)
    }
    [1]=>
    array(5) {
      [0]=>
      string(4) "verb"
      [1]=>
      array(1) {
        [0]=>
        string(50) "емитовати преко телевизије"
      }
      [2]=>
      array(1) {
        [0]=>
        array(2) {
          [0]=>
          string(50) "емитовати преко телевизије"
          [1]=>
          array(2) {
            [0]=>
            string(8) "televise"
            [1]=>
            string(8) "telecast"
          }
        }
      }
      [3]=>
      string(8) "telecast"
      [4]=>
      int(2)
    }
  }
  [2]=>
  string(2) "en"
  [3]=>
  array(1) {
    [0]=>
    array(8) {
      [0]=>
      string(39) "телевизијска емисија"
      [1]=>
      array(1) {
        [0]=>
        int(1)
      }
      [2]=>
      bool(true)
      [3]=>
      bool(false)
      [4]=>
      int(1000)
      [5]=>
      int(0)
      [6]=>
      int(2)
      [7]=>
      int(0)
    }
  }
  [4]=>
  array(1) {
    [0]=>
    array(5) {
      [0]=>
      string(8) "telecast"
      [1]=>
      int(1)
      [2]=>
      array(5) {
        [0]=>
        array(4) {
          [0]=>
          string(39) "телевизијска емисија"
          [1]=>
          int(1000)
          [2]=>
          bool(true)
          [3]=>
          bool(false)
        }
        [1]=>
        array(4) {
          [0]=>
          string(17) "ТВ пренос"
          [1]=>
          int(0)
          [2]=>
          bool(true)
          [3]=>
          bool(false)
        }
        [2]=>
        array(4) {
          [0]=>
          string(42) "објављен на телевизији"
          [1]=>
          int(0)
          [2]=>
          bool(true)
          [3]=>
          bool(false)
        }
        [3]=>
        array(4) {
          [0]=>
          string(50) "емитовати преко телевизије"
          [1]=>
          int(0)
          [2]=>
          bool(true)
          [3]=>
          bool(false)
        }
        [4]=>
        array(4) {
          [0]=>
          string(16) "телецаст"
          [1]=>
          int(0)
          [2]=>
          bool(true)
          [3]=>
          bool(false)
        }
      }
      [3]=>
      array(1) {
        [0]=>
        array(2) {
          [0]=>
          int(0)
          [1]=>
          int(8)
        }
      }
      [4]=>
      string(8) "telecast"
    }
  }
  [5]=>
  array(0) {
  }
  [6]=>
  int(5)
}
```

### CODE REVIEW

**Comment by Stichoza** [comment]
You're welcome! :+1:

**Comment by Stichoza** [comment]
I'll bumb version to **v3.2.2** to make this changes available without using `dev-master`.

**Comment by limonte** [comment]
@Stichoza great, thank you!

**Comment by Stichoza** [comment]
Hey, just to notify you. I [removed](b6914e479af01f1f30341eaa06e0a99f73cb10b5) `getResponse()` from static calls in v3.2.3 as it caused errors and there was no support for target/source languages. I also added some lines to test this feature.

**Comment by limonte** [comment]
@Stichoza Thank you, sorry for PR without test :)

**Pull request merged**
