### PR TITLE
Update URL and client

### PR DESCRIPTION
**Pull request by Razzo1987**
For me stop working without this fix

### CODE REVIEW

**Comment by Stichoza** [comment]
Strange, what error were you getting? Just tested and everything works fine for me.

**Comment by metikulos** [comment]
Fatal error</b>:  Uncaught ErrorException: Client error: `GET https://translate.google.com/translate_a/single?client=webapp&amp;hl=en&amp;dt=t&amp;dt=bd&amp;dt=at&amp;dt=ex&amp;dt=ld&amp;dt=md&amp;dt=qca&amp;dt=rw&amp;dt=rm&amp;dt=ss&amp;sl=auto&amp;tl=en&amp;q=Login&amp;ie=UTF-8&amp;oe=UTF-8&amp;multires=1&amp;otf=0&amp;pc=1&amp;trs=1&amp;ssel=0&amp;tsel=0&amp;kc=1&amp;tk=430331.41861` resulted in a `429 Too Many Requests` response:
--
  | &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot;&gt;
  | &lt;html&gt;
  | &lt;head&gt;&lt;meta http-equiv=&quot;content-type&quot; content=&quot;te (truncated...)
  | in /home/skytekgh/public_html/emigroup.skytekgh.com/vendor/stichoza/google-translate-php/src/GoogleTranslate.php:311

that is my problem

**Comment by Stichoza** [comment]
@metikulos 

1. The error you posted is not related to this pull request in any way.
2. Have you read the README file?

**Comment by taiviemthoi** [comment]
Hi @Stichoza 
https://github.com/Stichoza/google-translate-php/issues/23

```
<div class='love' id='green'>i love you<div><img src='https://exem.com' alt=''>
```

en->fr

```
<div class = 'love' id = "vert"> je t'aime <div> <: //exem.com' alt = ''>
```
id html is translated, or with other language (eg -> vi) it automatically capitalizes the css class

img src url with extra space

But when I try with client=gtx and the endpoint is  https://translate.googleapis.com/translate_a/single
then the translation is more accurate
```
<div class='love' id='green'>je t'aime<div><img src='https://exem.com' alt=''>
```

so could you please merge this request?

**Review by taiviemthoi — COMMENTED** [review]
LGTM

**Comment by sunxiyuan** [comment]
I encountered the same problem and successfully solved it by changing the client to gtx

**Comment by sunxiyuan** [comment]
To add, when the content is as follows, if the client is not changed to gtx, an exception will be returned
```
If a new user is created by WordPress, a new password will be randomly generated and the new user&#8217;s role will be set as %s. Manually changing the new user&#8217;s details will be necessary.
```

**Pull request merged**
