### PR TITLE
Code refactoring and some fixes

### PR DESCRIPTION
**Pull request by MASNathan**
- Code refactoring
- Added workaround for the array translattion
  - Thanks to the idea of @amprodes on issue #62 
- Fixed unit test issues

### CODE REVIEW

**Comment by Stichoza** [comment]
Can you tell more details about https://github.com/Stichoza/google-translate-php/pull/68/commits/83e7cfddd68282d469aae256baf85abc170d5ca3?

**Comment by natostanco** [comment]
sometimes spaces are added between chars, not sure if `||` is exempted, you might wanna use some regex `\| ?\| ?` also, recently google added some neural translations to chinese, hoping string merging like this does not mess something up...I still wonder if they just locked out arrays for all their public endpoints or not

**Comment by frzsombor** [comment]
@MASNathan Any updates on this?

**Comment by Stichoza** [comment]
Closing this because of v4.0.0 release

**Pull request closed without merging**
