### PR TITLE
Update GoogleTranslate.php

### PR DESCRIPTION
**Pull request by fcorbi**
Fix 400 BadRequest new release of google translate

### CODE REVIEW

**Comment by frzsombor** [comment]
Thanks for the super quick fix! I noticed your pull request before even noticing the problem on my server. Do you have a source for the fixes, or you found the solution yourself? And do you have any background information on these changes?

**Comment by DONSA** [comment]
Not sure if this is still maintained anymore. 
@fcorbi maybe you could make these changes in your fork?

**Comment by frzsombor** [comment]
@DONSA: I do think this project is maintained, maybe you just have to wait a bit more than a few hours for @Stichoza to respond. :)

**Comment by DONSA** [comment]
Branch `^3.2` doesn't have the latest changes that were made 7 months ago.
But you are right, waiting 5110 hours is not enough 🙂

**Comment by frzsombor** [comment]
I'm not sure if not maintaining an old branch equals to not maintaining a project, but anyway if you need the latest changes you can find them in the [latest release](https://github.com/Stichoza/google-translate-php/releases). But time (and hopefully Stichoza) will give you a better answer to your opened issue regarding this.

**Comment by Stichoza** [comment]
Sorry for being late. Merged. Thank you very much! 👍

**Comment by fcorbi** [comment]
You're welcome @Stichoza! thank you for the repo

@frzsombor no i don't have any background information, only had a big bug on server 😢 
@DONSA it's merged now, you can pull from here

**Pull request merged**
